services:
  - type: web
    name: estreamly-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    disk:
      name: user-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: /var/data
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@estreamly.com
      - key: APP_URL
        value: https://estreamly-scraper.onrender.com
      - key: SUPER_USER_EMAIL
        sync: false
